name = "DataCurator"
uuid = "dc8f3b54-baf0-491e-b310-4cc607c077ab"
authors = ["Ben Cardoen <26388277+bencardoen@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
