version: 2.1

jobs: # a basic unit of work in a run
  mac: # your job name
    macos:
      xcode: 14.2.0 # indicate your selected version of Xcode
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
    
      - run: |
          wget https://raw.githubusercontent.com/bencardoen/DataCurator.jl/main/scripts/install_mac.sh -O script.sh && chmod +x script.sh
          ./script.sh
  linux: 
    working_directory: /root/project/DataCurator.jl   # Clone into a directory whose name matches your Package.
    docker:
      - image: debian:stable
    steps:
      - run: |
          apt-get update -y
          apt-get install wget -y
          wget https://raw.githubusercontent.com/bencardoen/DataCurator.jl/main/scripts/install_debian.sh -O script.sh && chmod +x script.sh
          ./script.sh 

          
workflows:
  test_build:
    jobs:
      - mac
      - linux:
          requires:
            - mac
