
[global]
act_on_success=true
file_lists = ["table","channel", "objects"]
inputdirectory = "testdir"
[any]
conditions = ["is_csv_file","is_tif_file"]
actions=[["->", "table"],
         ["->", ["channel", "objects"]]]
