
[global]
act_on_success=true
owncloud_configuration="owncloud.json"
# SCP upload, instead of owncloud. This requires that you have SSH configured between the target systems.
file_lists = [{name="table", aggregator=[["shared_list_to_table","upload_to_scp"]]}]                                    
inputdirectory = "testdir"
[any]
all=true
conditions = ["is_csv_file"]
actions=[["add_to_file_list", "table"]]
