[global]
act_on_success=true
file_lists = [{name="table", transformer=["extract_columns", ["x1"]], aggregator="concat_to_table"}]
inputdirectory = "testdir"
[any]
all=true
conditions = ["is_csv_file"]
actions=[["add_to_file_list", "table"]]


#  transformer=["extract_columns", ["x1"]],
#  for each dataframe, only select column "X1"