
[global]
act_on_success=true
# Should have your Owncloud credentials
owncloud_configuration="owncloud.json"
# Aggregation is fine, but usually you want to have the result handy, so why not upload to owncloud?
file_lists = [{name="table", aggregator=[["shared_list_to_table","upload_to_owncloud"]]}]                                    
inputdirectory = "testdir"
[any]
all=true
conditions = ["is_csv_file"]
actions=[["add_to_file_list", "table"]]
