[global]
act_on_success=true
file_lists = [{name="table", transformer=["groupbycolumn", ["x1", "x2"], ["x3"], ["sum"], ["x3_sum"]], aggregator="concat_to_table"}]
inputdirectory = "testdir"
owncloud_configuration = "owncloud.json"
[any]
all=true
conditions = ["is_csv_file"]
actions=[["add_to_file_list", "table"]]
