[global]
act_on_success=true
inputdirectory = "testdir"
file_lists = [["table", "concat_to_table"]]
[any]
conditions = ["is_csv_file"]
# actions = ["warn_on_fail"]
actions=[["add_to_file_list", "table"]]
