[global]
act_on_success=true
inputdirectory = "testdir"
[any]
all=true
conditions = ["is_dir"]
# actions=[["count", "c1"]]
actions=[["image_colocalization", 3, "[1,2].tif", "is_2d_img", "/dev/shm"]]
# image_colocalization(t, 3, "[1,2].tif", "is_2d_img", t)
