# Superresolution alignment and colocalization.
[global]
act_on_success=true
inputdirectory = "testdir"
[any]
all=true
conditions = ["is_dir"]
# For each directory, find matching GSD files, do temporal and cross channel alignment, and then do colocalization on the results.
# Saves output in place
# Next, colocalization will be run on the resulting 2D images
# 500 = max distance between fiducials
# 5 = max number of fiducials to use
# The below only are implemented for Thunderstorm
# 1 = Focal plane (z) limiting (mode +- std)
# 15 = Maximum tolerable precision (nm)

# "filter" runs a basic adaptive intensity filter (mean + k std) on the images before colocalization.
# 1 = k, so here each channel has pixels removed if their intensity (point cloud density) is lower than u + 1 std
# alternatively, you can also say ..., "segment", 1 to run otsu thresholding on the images before colocalization, the `1' scales the otsu threshold value, higher is more stringent, lower is less stringent
actions=[["smlm_alignment",".bin", "is_gsd", 500, 4, 1, 15], ["image_colocalization", 3, "C[1,2].tif", "is_2d_img", "filter", 1]]
