# So far you've seen IF <condtiion> DO <action>
# But you can also do both, e.g. IF <condition> DO <action> ELSE DO <counter_action> 
[global]
act_on_success=true
inputdirectory = "testdir"
[any]
conditions=["is_csv_file"]
actions=[["log_to_file", "csvs.txt"]]
counter_actions = [["log_to_file", "non_csvs.txt"]]
