[global]
act_on_success=true
file_lists = [{name="table", transformer=["extract_sql_as_dataframe", "select * from temp"], aggregator="concat_to_table"}]
inputdirectory = "tx"
# save_tables_to_sqlite=true
[any]
all=true
conditions = ["is_file", "is_sqlite", ["sqlite_has_tables", ["temp"]]]
actions=[["->", "table"]]
