# Sometimes you just want to halt on first failure, if you're quickly testing an assumption or validity of your data. 
# Early exit allows you to do just that.
# Bottomup means you start at the deepest level first, and work your way up.
[global]
act_on_success = true
inputdirectory = "testdir"
traversal = "bottomup"
[any]
all = true
conditions = ["isfile", ["endswith", ".txt"]]
#If we see anything we don't expect, abort immediately.
#For parallel applications this can be a delayed abort, because other threads are dealing with different parts.
actions = ["warn_on_fail", "halt",]
