# Look for TIF files, save those to HDF5
# Do the same with CSV, but save thos in MAT format
[global]
act_on_success=true
inputdirectory = "testdir"
[any]
all=false
conditions = ["is_tif_file", "is_csv_file"]
actions=[["add_to_hdf5", "img.hdf5"], ["add_to_mat", "csv.mat"]]
