[global]
act_on_success = true
inputdirectory = "testdir"
regex=true
[any]
## Given
### /inputdirectory/a/b/c/q.txt
### /inputdirectory/a/b/z.txt
### Make it into
### /outputdirectory/q.txt, outputdirectory/z.txt
all=true
conditions = ["isfile", ["endswith", ".*.txt"]]
actions = [["flatten_to", "outdir"]]
