[global]
act_on_success=false
inputdirectory = "testdir"
hierarchical=true
[any]
conditions = ["never"]
actions=["show_warning"]
[level_1]
conditions = ["isdir"]
actions = ["show_warning"]
[level_2]
conditions = ["isfile"]
actions = ["show_warning"]
