[global]
act_on_success=false
inputdirectory = "testdir"
[any]
conditions = ["never"]
actions=["show_warning"]
[1]
conditions = ["isdir"]
actions = ["show_warning"]
[2]
conditions = ["is_file"]
actions = ["show_warning"]
