# Image processing of tif files, using the LOG technique
[global]
act_on_success=true
inputdirectory = "testdir"
[any]
conditions=["is_tif_file"]
actions=[{name_transform=["tolowercase"], content_transform=[ ["gaussian", 3],
                                                                "laplacian",
                                                                ["threshold_image", "abs >", 0.01],
                                                                ["apply_to_image", ["abs"]],
                                                                "otsu_threshold_image",
                                                                "erode_image"], mode="copy"}]
# Full syntax
# {name_transform=[entry+], content_transform=[entry+], mode={copy, move, inplace}}
# ["gaussian", sigma ] # Smooth the image with a Gaussian kernel of width sigma
# ["threshold_image", "abs >", 0.01],  # Threshold, using absolute value, < 0.01 is set to 0
# ["apply_to_image", ["abs"]] # Set all pixels to absolute value
# "otsu_threshold_image", # Perform otsu thresholding
# "erode_image"], # Erosion removes small isolated pixels 
# mode="copy"}]   # This ensures the original is not changed, but a copy is created with the output