
# Example of the full transformation notation
# For each tif file, do a max projection along Y, then binarize the resulting image
[global]
act_on_success=true
inputdirectory = "testdir"
[any]
conditions=["is_tif_file"]
actions=[{name_transform=["tolowercase"], content_transform=[["slice_image", [1,3], [[5,10],[4,7]]]], mode="copy"}]

## Image slicing
## single slice
## slice_image 1, 3

## range
## slice_image dim, from, to
## all dimensions, ranges
## slice_image [d1,d2,...], [[x1,x2],[y1,y2],...]
