[global]
act_on_success = true
inputdirectory = "testdir"
regex=true
[any]
all=true
# You can negate conditions with "not"
conditions = ["isfile", ["not", "endswith", ".*.txt"]]
actions = [["flatten_to", "outdir"], "warn_on_fail"]
