[global]
hierarchical=true
inputdirectory = "testdir"
## Define common conditions and actions
common_actions = {react=["show_warning", ["log_to_file", "errors.txt"], "remove"]}
common_conditions = {is_3d_channel=["is_tif_file", "is_3d_img", "ends_with_integer"]}
[any]
conditions=["always_fails"]
actions=["react"]
[1]
conditions=["isdir"]
actions=["react"]
[2]
conditions=["is_3d_channel"]
actions=["react"]
