[global]
act_on_success=true
# hierarchical=true
inputdirectory = "testdir"
outputdirectory = "outdir"
common_actions = {react=[["all", "show_warning", ["log_to_file", "errors.txt"], "remove"]]}
common_conditions = {is_3d_channel=[["all", "is_tif_file", "is_3d_img", "ends_with_integer"]]}
[any]
conditions=["is_3d_channel"]
actions=["react"]
# [level_1]
# conditions=["isdir"]
# actions=["react"]
# [level_2]
# conditions=["is_3d_channel"]
# actions=["react"]
