[global]
act_on_success=true
inputdirectory = "testdir"
scp_configuration = "ssh.json"
[any]
all=true
conditions = ["is_csv_file"]
actions=[["change_path", "/home/bcardoen/scratch"], "upload_to_scp"]
