# Shells scripts can be sensitive to spaces in names, this replaces those with `_` and lowercases the name
[global]
act_on_success=true
inputdirectory = "testdir"
[any]
conditions = ["has_whitespace"]
actions=[["transform_inplace", ["whitespace_to", '_'], "tolowercase"]]
