[global]
inputdirectory="testdir"
[any]
conditions=["is_tif_file"]
actions=[{name_transform=["tolowercase"], content_transform=[
                        ["slice_image", [1,3],[[10,25],[10,25]]],
                        ["gaussian", 1],
                         "laplacian",
                        ["threshold_image", "abs >", 0.001],
                        ["apply_to_image", ["abs"]],
                         "otsu_threshold_image",
                         "erode_image"
                        ], mode="copy"}
     ]
